#!/usr/bin/env python3
"""
make-serape.py — emits assets/img/serape.svg

A serape stripe: vertical bands of colour separated by checkered pinstripes,
with the woven dash texture of the cloth across every band.

WHY THIS IS GENERATED AND NOT A PHOTOGRAPH. The VA sent a picture of a real
serape and asked for it on the site. A photograph of somebody else's blanket is
stock artwork with unknown provenance, and brand.css has thrown out invented
ornament twice already for exactly that reason. But a serape is not a picture —
it is a SEQUENCE: bands of a given width in a given colour, a weave on a grid,
pinstripes at the joins. That makes it the same kind of thing as the greca, and
it passes the rule at the top of brand.css: if the idea can be expressed as a
script that emits it, it is allowed.

The gain over the photograph is that every colour is ours. The bands are drawn
from the Quetzalcoatl accents in brand.css — the ones already carrying the fleet
rules — plus the livery red and blue, so the ribbon reads as this airline's
cloth rather than as a picture of cloth.

Keep the tile's proportions if you retune it: the CSS sizes it in px so the
weave stays the same size however wide the ribbon gets, and stretching one axis
alone turns the square weave into a smear.
"""

import pathlib

CELL = 4          # one thread crossing, px
ROWS = 15         # tile height in cells -> 60px
OUT = pathlib.Path(__file__).resolve().parent.parent / "assets" / "img" / "serape.svg"

# Straight off :root in brand.css. Nothing here is mixed or invented.
C = {
    "red":       "#D8102F",   # --am-red, the fuselage swoosh
    "rosa":      "#D6337E",   # --am-rosa
    "marigold":  "#F2A03D",   # --am-marigold
    "clay":      "#C05A2E",   # --am-clay
    "jade":      "#0E8C5A",   # --am-jade
    "turquoise": "#0E9BAA",   # --am-turquoise
    "cobalt":    "#1B5FC1",   # --am-cobalt
    "blue":      "#0C2C64",   # --am-blue
    "navy":      "#0A1D3B",   # --am-navy, the dark half of a pinstripe
    "paper":     "#FFFFFF",   # --am-paper, the light half
}

# (colour key, width in cells). `None` marks a checkered pinstripe, which is
# what a real serape puts at a colour change — the join is never a hard butt.
BANDS = [
    ("red", 7), (None, 1), ("rosa", 5), ("marigold", 6), ("clay", 5),
    (None, 1), ("jade", 6), ("turquoise", 5), (None, 1),
    ("cobalt", 6), ("blue", 5), (None, 1), ("red", 7),
]


def shade(hex_colour, factor):
    """Lighten (>1) or darken (<1) a colour, clamped. The weave is the same
    colour at two values, not two different colours."""
    h = hex_colour.lstrip("#")
    rgb = [int(h[i:i + 2], 16) for i in (0, 2, 4)]
    return "#%02X%02X%02X" % tuple(max(0, min(255, round(v * factor))) for v in rgb)


def main():
    parts, x = [], 0
    for key, cells in BANDS:
        w = cells * CELL
        if key is None:
            # The pinstripe: alternating light and dark cells down the column,
            # which is what reads as the checker in the cloth.
            for r in range(ROWS):
                fill = C["paper"] if r % 2 == 0 else C["navy"]
                parts.append(f'<rect x="{x}" y="{r * CELL}" width="{w}" height="{CELL}" fill="{fill}"/>')
        else:
            base = C[key]
            parts.append(f'<rect x="{x}" y="0" width="{w}" height="{ROWS * CELL}" fill="{base}"/>')
            # The weave. Each row is a run of dashes half a cell out of step
            # with the row above it, in the same colour lifted a little — the
            # thread catching the light as it passes over the warp.
            lit = shade(base, 1.16)
            for r in range(ROWS):
                offset = (CELL // 2) if r % 2 else 0
                cx = x + offset
                while cx < x + w:
                    dash = min(CELL - 1, x + w - cx)
                    if dash > 0:
                        parts.append(
                            f'<rect x="{cx}" y="{r * CELL}" width="{dash}" height="{CELL - 1}" '
                            f'fill="{lit}" opacity=".5"/>')
                    cx += CELL * 2
        x += w

    svg = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!--\n"
        "  serape.svg — vertical bands, checkered pinstripes, woven texture.\n\n"
        "  GENERATED by tools/make-serape.py from the palette in brand.css.\n"
        "  Do not hand-edit; retune the script and re-run it.\n"
        f"  Tile: {x} x {ROWS * CELL}px, one cell = {CELL}px.\n"
        "-->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{x}" height="{ROWS * CELL}" '
        f'viewBox="0 0 {x} {ROWS * CELL}" shape-rendering="crispEdges">\n'
        + "\n".join(parts)
        + "\n</svg>\n"
    )
    OUT.write_text(svg, encoding="utf-8")
    print(f"wrote {OUT} — tile {x}x{ROWS * CELL}px")
    print(f"  keep --serape-tile in brand.css at {x}px {ROWS * CELL}px")


if __name__ == "__main__":
    main()
