"""Emit assets/img/greca.svg — a stepped-fret band, and greca-tile.svg.

A greca is the stepped fret that runs as a band across Mixtec and Zapotec
stonework — the mosaics at Mitla are the ones everybody has seen. It is the one
Mexican ornament that is architectural rather than pictorial: it is built out of
right angles on a grid, which is why it can be generated here instead of drawn
by hand, and why it sits beside the ruled-feather device without either one
looking out of place.

    assets/img/greca.svg       one band tile, repeats horizontally
    assets/img/greca-tile.svg  the band mirrored into a 2-row block, for fields

Geometry, in grid units (u), for one repeat:

      ┌──┐        ┌──┐          the fret rises in steps to a plateau, drops
    ──┘  └──┐  ┌──┘  └──        back in steps, and inverts — so consecutive
            └──┘                repeats interlock rather than merely abut.

Everything is derived from U, STEPS and STROKE below, so the proportions can be
retuned without re-drawing anything. Output is monochrome: brand.css paints it
through a CSS mask exactly like the mark and the stripes, so one file serves
every colour and both themes.

    python3 tools/make-greca.py
"""
import pathlib

IMG = pathlib.Path(__file__).resolve().parent.parent / "assets/img"
DST = IMG / "greca.svg"
DST_TILE = IMG / "greca-tile.svg"

U = 6          # grid unit in px
STEPS = 3      # steps up (and down) on each side of a plateau
STROKE = 6     # line thickness, in px — one unit reads best
PLATEAU = 2    # units of flat run at the top and bottom of each fret


def fret_points():
    """One repeat of the fret, as (x, y) in grid units.

    Built as: climb STEPS, run along the plateau, descend STEPS, run along the
    trough. Drawn from the trough so the band is vertically centred on its own
    height and tiles cleanly against a copy of itself.
    """
    pts = [(0, STEPS)]
    x, y = 0, STEPS
    for _ in range(STEPS):          # up: right one, up one
        x += 1; pts.append((x, y))
        y -= 1; pts.append((x, y))
    x += PLATEAU; pts.append((x, y))   # the plateau
    for _ in range(STEPS):          # down: right one, down one
        x += 1; pts.append((x, y))
        y += 1; pts.append((x, y))
    x += PLATEAU; pts.append((x, y))   # the trough
    return pts


PTS = fret_points()
REPEAT_W = PTS[-1][0]                  # units consumed by one repeat
BAND_H = STEPS                         # units from trough to plateau

W = REPEAT_W * U
H = BAND_H * U + STROKE                # room for the stroke at both extremes


def path_d(points, flip=False):
    out = []
    for i, (px, py) in enumerate(points):
        y = (BAND_H - py) if flip else py
        out.append(f"{'M' if i == 0 else 'L'}{px * U},{round(y * U + STROKE / 2, 2)}")
    return " ".join(out)


def svg(body, w, h, note):
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!--
{note}

  GENERATED by tools/make-greca.py — retune U / STEPS / STROKE / PLATEAU there
  and re-run, do not hand-edit the coordinates.

  Monochrome on purpose: brand.css paints it through a CSS mask, same as the
  mark and the stripes, so one file serves any colour and both themes. The tile
  is an exact multiple of the fret repeat, so the rhythm never breaks at a seam.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}"
     width="{w}" height="{h}" fill="none" stroke="#000"
     stroke-width="{STROKE}" stroke-linecap="square" stroke-linejoin="miter">
{body}
</svg>
'''


# --- The band: one row of frets, for a rule across the page ------------------
DST.write_text(svg(
    f'  <path d="{path_d(PTS)}"/>',
    W, H,
    "  greca.svg — a stepped fret band, the ornament off Mixtec and Zapotec\n"
    "  stonework. Repeats horizontally as a rule."
), encoding="utf-8")

# --- The tile: the band over its own mirror, for a faint field ---------------
# Mirroring rather than repeating gives the block a horizontal axis, so tiled
# large it reads as masonry courses instead of as one row copied downward.
row2 = H - STROKE
DST_TILE.write_text(svg(
    f'  <path d="{path_d(PTS)}"/>\n'
    f'  <g transform="translate(0,{row2})">\n'
    f'    <path d="{path_d(PTS, flip=True)}"/>\n'
    f'  </g>',
    W, H + row2,
    "  greca-tile.svg — the same fret over its own mirror, as a two-course\n"
    "  block for tiling across a field."
), encoding="utf-8")

print(f"fret repeat {REPEAT_W}u, band {BAND_H}u, stroke {STROKE}px")
print(f"wrote {DST.name}: {W} x {H}")
print(f"wrote {DST_TILE.name}: {W} x {H + row2}")
print(f"  -> --greca-w: {W}px / --greca-h: {H}px in assets/brand.css")
