"""Emit the ruled-feather device from the logo, as two masks.

Aeroméxico's mark carries a block of horizontal rules to the left of the eagle:
bars flush to a common right edge with a ragged left edge. Grupo AMX Virtual run
the same device down the edges of their pages, which is what this reproduces.

    assets/img/stripes.svg         bars flush RIGHT, ragged left edge
    assets/img/stripes-mirror.svg  the same profile flipped, flush LEFT

Two files rather than one flipped in CSS because both rails are painted by a
single pseudo-element carrying two mask layers, and a transform there would
turn the whole element — including the other rail — around with it.

The bar lengths are NOT invented. They are measured off the stripe block in
assets/img/full-logo.webp: for each row of that block, the script finds the run
of ink ending at the block's right edge and records how far left it reaches.
That ragged profile is the pattern. Re-run after replacing the logo and the
rhythm follows the new artwork:

    python3 tools/make-stripes.py

Output is monochrome so brand.css can paint it through a CSS mask, same as the
mark — one file, any colour, both themes.
"""
import pathlib
from PIL import Image

IMG = pathlib.Path(__file__).resolve().parent.parent / "assets/img"
SRC = IMG / "full-logo.webp"
DST = IMG / "stripes.svg"
DST_MIRROR = IMG / "stripes-mirror.svg"

INK = 200          # darker than this counts as ink
BAR = 6            # bar thickness in the emitted tile
GAP = 7            # gap between bars
WIDTH = 100        # tile width; bar lengths are scaled into this

g = Image.open(SRC).convert("L")
w, h = g.size
px = g.load()

# The stripe block sits in the left third of the mark. Find, per row, the run
# of ink that ends nearest the block's right edge, and measure its extent.
LEFT = int(w * 0.34)
rows = {}
for y in range(h):
    ink = [x for x in range(LEFT) if px[x, y] < INK]
    if not ink:
        continue
    runs, start = [], ink[0]
    for i in range(1, len(ink)):
        if ink[i] != ink[i - 1] + 1:
            runs.append((start, ink[i - 1]))
            start = ink[i]
    runs.append((start, ink[-1]))
    rows[y] = runs

assert rows, "no ink found in the left third of the logo"

# The ruled block is the right edge that RECURS across rows — that is what makes
# it a block of rules rather than a silhouette. Count every run's right edge,
# not just the furthest one per row: the furthest is the eagle's head, which
# sits to the right of the rules and would yield 28 near-identical bars.
from collections import Counter
block_right = Counter(r[1] for runs in rows.values() for r in runs).most_common(1)[0][0]

# Per row, the run that lands on that edge. Its left end is the ragged profile.
lefts = []
for y in sorted(rows):
    on_edge = [r for r in rows[y] if abs(r[1] - block_right) <= 2]
    if on_edge:
        lefts.append(min(r[0] for r in on_edge))
lo, hi = min(lefts), max(lefts)
lengths = [(block_right - L) / (block_right - lo) for L in lefts]

print(f"stripe block right edge x={block_right}, left edges {lo}..{hi}")
print(f"{len(lengths)} bars, relative lengths "
      f"{min(lengths):.2f}..{max(lengths):.2f}")

pitch = BAR + GAP
height = len(lengths) * pitch


def emit(dst, flush, edge_note):
    """Write one mask. `flush` is "right" (x offset) or "left" (x = 0)."""
    bars = "\n".join(
        f'  <rect x="{WIDTH - round(f * WIDTH, 1) if flush == "right" else 0}" '
        f'y="{i * pitch}" '
        f'width="{round(f * WIDTH, 1)}" height="{BAR}" rx="{BAR / 2}"/>'
        for i, f in enumerate(lengths)
    )
    dst.write_text(f'''<?xml version="1.0" encoding="UTF-8"?>
<!--
  {dst.name} — the ruled-feather device off the Aeroméxico mark.

{edge_note}

  GENERATED by tools/make-stripes.py, which measures the ragged profile off
  assets/img/full-logo.webp rather than inventing one — do not hand-edit,
  re-run the script.

  Monochrome on purpose: brand.css paints it through a CSS mask, so one file
  serves any colour and both themes. It tiles vertically, so the tile height is
  an exact multiple of the bar pitch ({BAR} + {GAP}) and the rhythm never breaks
  across the seam.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {height}"
     width="{WIDTH}" height="{height}" preserveAspectRatio="none" fill="#000">
{bars}
</svg>
''', encoding="utf-8")
    print(f"wrote {dst.name}: {WIDTH} x {height}, {len(lengths)} bars, pitch {pitch}")


emit(DST, "right", """  Bars flush to the right edge with a ragged left edge, the way the rules sit
  beside the eagle in the logo.""")
emit(DST_MIRROR, "left", """  The same measured profile flipped: bars flush LEFT, ragged right, for the
  left-hand rail. Mirrored here rather than with a CSS transform because one
  pseudo-element paints both rails, and a transform would turn both.""")
print(f"  -> set --stripe-tile: {height}px in assets/brand.css")
