#!/usr/bin/env python3
"""
Aeromexico Virtual — make-worldmap.py

Emits assets/js/world.js: the world's coastlines as one SVG path, projected
Robinson, for the route map on /network.

This obeys the rule at the top of brand.css. The map is not drawn artwork — it
is Natural Earth's public-domain 1:110m land polygons, reprojected and
simplified by this script. Re-run it and you get the same map; change the
tolerance and you get a coarser or finer one. Nothing here is illustrated.

    curl -O https://raw.githubusercontent.com/nvkelso/natural-earth-vector/\
master/geojson/ne_110m_land.geojson
    python3 tools/make-worldmap.py ne_110m_land.geojson

Robinson is used rather than equirectangular because the network reaches Tokyo,
Seoul, Madrid and Santiago: on a plate carrée those sit at wildly wrong
apparent distances from Mexico City, and the map's whole job is to show that
the airline flies a long way. The same projection is implemented in
assets/js/map.js so the airport dots land on the coastlines.
"""

import json, math, sys

# Robinson's published table, at 5-degree steps of latitude.
# X = length of the parallel, Y = its distance from the equator, both as a
# fraction of the equator's half-length.
ROBINSON = [
    (1.0000, 0.0000), (0.9986, 0.0620), (0.9954, 0.1240), (0.9900, 0.1860),
    (0.9822, 0.2480), (0.9730, 0.3100), (0.9600, 0.3720), (0.9427, 0.4340),
    (0.9216, 0.4958), (0.8962, 0.5571), (0.8679, 0.6176), (0.8350, 0.6769),
    (0.7986, 0.7346), (0.7597, 0.7903), (0.7186, 0.8435), (0.6732, 0.8936),
    (0.6213, 0.9394), (0.5722, 0.9761), (0.5322, 1.0000),
]

def robinson(lat, lon):
    """(lat, lon) in degrees -> (x, y) in a 0..1 box, y down."""
    a = min(abs(lat), 89.999)
    i = min(int(a / 5.0), 17)
    t = (a - i * 5.0) / 5.0
    xr = ROBINSON[i][0] + (ROBINSON[i + 1][0] - ROBINSON[i][0]) * t
    yr = ROBINSON[i][1] + (ROBINSON[i + 1][1] - ROBINSON[i][1]) * t
    if lat < 0:
        yr = -yr
    # Normalised into a unit box: x across the full width, y across the full
    # height. The box itself is ASPECT high per unit wide, which is Robinson's
    # own 0.5072 — apply it when sizing, not here.
    x = 0.5 + (lon / 180.0) * xr * 0.5
    y = 0.5 - yr * 0.5
    return x, y

def perp(p, a, b):
    (px, py), (ax, ay), (bx, by) = p, a, b
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return math.hypot(px - ax, py - ay)
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))

def simplify(pts, tol):
    """Douglas-Peucker, iterative so a long coastline cannot blow the stack."""
    if len(pts) < 3:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        lo, hi = stack.pop()
        worst, wi = 0.0, -1
        for i in range(lo + 1, hi):
            d = perp(pts[i], pts[lo], pts[hi])
            if d > worst:
                worst, wi = d, i
        if wi >= 0 and worst > tol:
            keep[wi] = True
            stack.append((lo, wi))
            stack.append((wi, hi))
    return [p for p, k in zip(pts, keep) if k]

def rings(geom):
    t = geom["type"]
    if t == "Polygon":
        return geom["coordinates"]
    if t == "MultiPolygon":
        return [r for poly in geom["coordinates"] for r in poly]
    return []

ASPECT = 0.5072   # Robinson's height-to-width ratio, 1.3523 / (0.8487 * pi)


def main(src, dst="assets/js/world.js", tol=0.0011, min_area=0.000045):
    gj = json.load(open(src))
    W = 2000.0
    H = round(W * ASPECT)
    out = []
    for feat in gj["features"]:
        for ring in rings(feat.get("geometry") or {}):
            pts = []
            for lon, lat in ring:
                x, y = robinson(lat, lon)
                pts.append((x * W, y * H))
            pts = simplify(pts, tol * W)
            if len(pts) < 4:
                continue
            # Shoelace, to drop specks that survive simplification as triangles.
            area = abs(sum(pts[i][0] * pts[i - 1][1] - pts[i - 1][0] * pts[i][1]
                           for i in range(len(pts)))) / 2.0
            if area < min_area * W * H:
                continue
            d = "M" + " ".join(f"{x:.1f},{y:.1f}" for x, y in pts) + "Z"
            out.append(d)

    path = "".join(out)
    js = (
        "/* GENERATED by tools/make-worldmap.py — do not edit by hand.\n"
        "   Natural Earth 1:110m land (public domain), Robinson projection,\n"
        f"   simplified to {tol} of the map width. Viewbox {int(W)}x{int(H)}. */\n"
        f"window.AMV_WORLD = {{ w: {int(W)}, h: {int(H)}, land: '{path}' }};\n"
    )
    open(dst, "w").write(js)
    print(f"{dst}: {len(out)} rings, {len(js) / 1024:.1f} kB")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "ne_110m_land.geojson")
