"""Emit assets/img/serpent.svg — a Quetzalcóatl frieze band.

The feathered serpent already runs through this brand: the accent palette in
brand.css is pulled off the Quetzalcóatl glyphs down the side of XA-ADL, and the
hero artwork carries one. This is the same idea as a band — the chevron body of
a serpent frieze with a rhomb riding in each fold, the way serpent courses are
cut into Mesoamerican stonework.

NOT the eagle-and-serpent of the national coat of arms. That is the escudo
nacional, its reproduction is regulated under the Ley sobre el Escudo, la
Bandera y el Himno Nacionales, and this is a virtual airline with no claim on
it. The eagle on this site is Aeroméxico's own Caballero Águila (mark.svg) and
the serpent is this frieze; put together they read as the airline's two motifs,
not as a state emblem.

Generated from parameters like the greca — chevrons and rhombs on a grid, so it
is geometry rather than an illustration, per the rule at the top of brand.css:

    python3 tools/make-serpent.py

Monochrome, painted through a CSS mask, so one file serves any colour and both
themes.
"""
import pathlib

IMG = pathlib.Path(__file__).resolve().parent.parent / "assets/img"
DST = IMG / "serpent.svg"

U = 8          # grid unit in px
RUN = 4        # units from a fold to the next apex — half a repeat
RISE = 3       # units from trough to crest
STROKE = 5     # body thickness in px
RHOMB = 1.15   # rhomb half-diagonal, in units
REPEATS = 2    # folds per emitted tile; 2 keeps the seam on a crest


def chevron(reps):
    """The serpent's body: a zigzag between RISE and 0, apex every RUN.

    Runs one segment PAST the tile at each end. A path that stops exactly on
    the tile edge ends in a butt cap there, so the miter that should form at
    the seam never does and every repeat shows a small vertical nick. With the
    overhang the join is real geometry and the viewBox simply crops it.
    """
    pts = []
    for i in range(-1, reps * 2 + 2):
        x = i * RUN
        pts.append((x, RISE if i % 2 else 0))
    return pts


def rhombs(reps):
    """One rhomb riding in each fold.

    Placed on the ODD multiples of RUN — the folds that fall strictly inside
    the tile. The even ones sit on the tile edges, where a rhomb is cropped in
    half by the viewBox and its other half never arrives, because the next tile
    starts with the same crop rather than the remainder.
    """
    return [(RUN * (2 * i + 1), RISE * 0.55) for i in range(reps)]


PTS = chevron(REPEATS)
W = REPEATS * 2 * RUN * U          # the tile, not the overhung path
H = RISE * U + STROKE


def sx(v):
    return round(v * U, 2)


def sy(v):
    return round(v * U + STROKE / 2, 2)


body = " ".join(
    f"{'M' if i == 0 else 'L'}{sx(x)},{sy(y)}" for i, (x, y) in enumerate(PTS)
)
diamonds = "\n".join(
    f'  <path d="M{sx(cx)},{sy(cy - RHOMB)} L{sx(cx + RHOMB)},{sy(cy)} '
    f'L{sx(cx)},{sy(cy + RHOMB)} L{sx(cx - RHOMB)},{sy(cy)} Z" '
    f'fill="#000" stroke="none"/>'
    for cx, cy in rhombs(REPEATS)
)

DST.write_text(f'''<?xml version="1.0" encoding="UTF-8"?>
<!--
  serpent.svg — a Quetzalcóatl frieze: the chevron body of a serpent course
  with a rhomb riding in each fold.

  NOT the eagle-and-serpent of the national coat of arms. That is the escudo
  nacional and its reproduction is regulated; this is the feathered serpent the
  brand already carries (the accent palette is taken off the Quetzalcóatl
  glyphs on XA-ADL). Paired with mark.svg — Aeroméxico's own Caballero Águila —
  it reads as the airline's two motifs, not as a state emblem.

  GENERATED by tools/make-serpent.py — retune U / RUN / RISE / STROKE / RHOMB
  there and re-run, do not hand-edit the coordinates.

  Monochrome on purpose: brand.css paints it through a CSS mask, so one file
  serves any colour and both themes. The tile ends on a crest, so it repeats
  horizontally without a kink at the seam.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}"
     width="{W}" height="{H}" fill="none" stroke="#000"
     stroke-width="{STROKE}" stroke-linecap="butt" stroke-linejoin="miter">
  <path d="{body}"/>
{diamonds}
</svg>
''', encoding="utf-8")

print(f"repeat {PTS[-1][0]}u wide, {RISE}u tall, {REPEATS} folds")
print(f"wrote {DST.name}: {W} x {H}")
print(f"  -> --serpent-band: {W}px {H}px in assets/brand.css")
