#!/usr/bin/env python3
"""
Aeromexico Virtual — make-globe.py

Emits assets/js/globe-land.js: which points of a regular latitude/longitude
grid fall on land, as a packed bitmask, for the dot globe on /network.

This obeys the rule at the top of brand.css. The globe is not drawn artwork —
it is Natural Earth's public-domain 1:110m land polygons, sampled on a grid.
Re-run it and you get the same globe; change the step and you get a coarser or
finer one. Nothing here is illustrated.

    curl -O https://raw.githubusercontent.com/nvkelso/natural-earth-vector/\
master/geojson/ne_110m_land.geojson
    python3 tools/make-globe.py ne_110m_land.geojson

Why a bitmask rather than a list of coordinates: the grid is regular, so the
coordinates are implied by the index and only the land/sea answer has to ship.
Roughly 7,000 land points as explicit pairs is 30 kB; as one bit per grid cell
it is under 4 kB, and the browser expands it to unit vectors once at startup.

The step is ANGULAR in both axes, which is why the dots crowd towards the
poles. That is not an artefact to correct — it is what a lat/lon graticule
does on a sphere, and it is the reason the globe reads as a globe the moment
it starts turning.
"""

import base64, json, sys

STEP = 1.7  # degrees, both axes


def rings(geom):
    """Every linear ring in a Polygon or MultiPolygon, outer and holes alike."""
    t, c = geom['type'], geom['coordinates']
    if t == 'Polygon':
        return list(c)
    if t == 'MultiPolygon':
        return [r for poly in c for r in poly]
    return []


def build_index(polys, lat0, step, rows):
    """Ring edges bucketed by latitude band, so each row tests a handful of
       edges instead of all sixteen thousand."""
    buckets = [[] for _ in range(rows)]
    for ring in polys:
        for i in range(len(ring) - 1):
            x1, y1 = ring[i][0], ring[i][1]
            x2, y2 = ring[i + 1][0], ring[i + 1][1]
            if y1 == y2:
                continue
            lo, hi = (y1, y2) if y1 < y2 else (y2, y1)
            # Rows run north to south: row r has latitude lat0 - r*step.
            r_lo = int((lat0 - hi) / step)
            r_hi = int((lat0 - lo) / step)
            for r in range(max(0, r_lo), min(rows - 1, r_hi) + 1):
                buckets[r].append((x1, y1, x2, y2))
    return buckets


def main(path):
    gj = json.load(open(path))
    polys = []
    for f in gj['features']:
        polys += rings(f['geometry'])

    rows = int(round(180.0 / STEP))
    cols = int(round(360.0 / STEP))
    lat0 = 90.0 - STEP / 2.0
    lon0 = -180.0 + STEP / 2.0

    buckets = build_index(polys, lat0, STEP, rows)

    bits = bytearray((rows * cols + 7) // 8)
    land = 0
    for r in range(rows):
        lat = lat0 - r * STEP
        edges = buckets[r]
        if not edges:
            continue
        # Ray casting eastward along this parallel. Crossings are collected
        # once per row and sorted, then every cell in the row is answered by
        # its position in that list — one pass instead of one per cell.
        xs = []
        for x1, y1, x2, y2 in edges:
            if (y1 > lat) != (y2 > lat):
                xs.append(x1 + (lat - y1) * (x2 - x1) / (y2 - y1))
        if not xs:
            continue
        xs.sort()
        n = len(xs)
        j = 0
        for c in range(cols):
            lon = lon0 + c * STEP
            while j < n and xs[j] <= lon:
                j += 1
            # `j` crossings lie west of this point: odd means inside.
            if j & 1:
                k = r * cols + c
                bits[k >> 3] |= 0x80 >> (k & 7)
                land += 1

    out = (
        '/* GENERATED by tools/make-globe.py — do not edit by hand.\n'
        '   Natural Earth 1:110m land (public domain), sampled on a %.1f-degree\n'
        '   lat/lon grid. One bit per cell, row-major from the north pole, MSB\n'
        '   first. %d of %d cells are land. */\n'
        'window.AMV_GLOBE_LAND = { step: %s, rows: %d, cols: %d, lat0: %s, lon0: %s,\n'
        '    bits: \'%s\' };\n'
    ) % (STEP, land, rows * cols, STEP, rows, cols, lat0, lon0,
         base64.b64encode(bytes(bits)).decode('ascii'))

    open('assets/js/globe-land.js', 'w').write(out)
    sys.stderr.write('globe-land.js: %d land points of %d cells (%d rows x %d cols), %d bytes\n'
                     % (land, rows * cols, rows, cols, len(out)))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'ne_110m_land.geojson')
